# Generated by Django 3.2 on 2023-03-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testa'),
    ]

    operations = [
        migrations.AddField(
            model_name='testa',
            name='b',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
