# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-06 01:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('buildScript', models.TextField(verbose_name='Build script')),
                ('productionSettings', models.TextField(verbose_name='Production settings')),
                ('stageSettings', models.TextField(verbose_name='Stage settings')),
                ('developmentSettings', models.TextField(verbose_name='Development settings')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('logFile', models.CharField(max_length=255, verbose_name='Log file')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('image', models.CharField(max_length=255, verbose_name='Image ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AppService', verbose_name='App service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('logFile', models.CharField(max_length=255, verbose_name='Log file')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('container', models.CharField(max_length=255, verbose_name='Container ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AppService', verbose_name='App service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canBuild', models.BooleanField(default=True, verbose_name='Can build')),
                ('canDeploy', models.BooleanField(default=True, verbose_name='Can deploy')),
                ('canRemove', models.BooleanField(default=True, verbose_name='Can remove')),
                ('canCreateDB', models.BooleanField(default=True, verbose_name='Can create DB')),
                ('canResetDB', models.BooleanField(default=True, verbose_name='Can reset DB')),
                ('privateKey', models.FileField(upload_to='uploads/keys/%Y%m%d/', verbose_name='Private key')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='build',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
