# Generated by Django 2.2.7 on 2019-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='success',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='success',
        ),
        migrations.AddField(
            model_name='build',
            name='mode',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGE', 'Stage'), ('DEVELOPMENT', 'Development')], default='PRODUCTION', max_length=255, verbose_name='Mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='SUCCESS', max_length=255, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploy',
            name='mode',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGE', 'Stage'), ('DEVELOPMENT', 'Development')], default='PRODUCTION', max_length=255, verbose_name='Mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploy',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='SUCCESS', max_length=255, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
