# Generated by Django 2.2.7 on 2019-11-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191106_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Image ID'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='container',
            field=models.CharField(max_length=255, null=True, verbose_name='Container ID'),
        ),
    ]
