# Generated by Django 2.2.7 on 2019-11-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191106_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='mode',
        ),
    ]
