# Generated by Django 2.2.7 on 2019-11-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191106_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='mode',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGE', 'Stage'), ('DEVELOPMENT', 'Development')], default='PRODUCTION', max_length=255, verbose_name='Mode'),
            preserve_default=False,
        ),
    ]
