# Generated by Django 2.2.7 on 2019-11-12 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20191106_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='privateKey',
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyName', models.CharField(max_length=255, verbose_name='Key name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Key', verbose_name='Key'),
            preserve_default=False,
        ),
    ]
