# Generated by Django 2.2.7 on 2019-11-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191112_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppService',
            new_name='App',
        ),
    ]
