# Generated by Django 2.2.7 on 2019-11-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191112_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Image name'),
        ),
        migrations.AddField(
            model_name='build',
            name='version',
            field=models.CharField(max_length=255, null=True, verbose_name='Image version'),
        ),
        migrations.AlterField(
            model_name='build',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.App', verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.App', verbose_name='App'),
        ),
    ]
