# Generated by Django 2.2.7 on 2019-11-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191112_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
