# Generated by Django 2.2.7 on 2020-01-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_app_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='testScript',
            field=models.FileField(default=None, null=True, upload_to='uploads/', verbose_name='Test script'),
        ),
    ]
