# Generated by Django 2.2.7 on 2020-02-06 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_app_testscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('logFile', models.CharField(max_length=255, verbose_name='Log file')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=255, verbose_name='Status')),
                ('mode', models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGE', 'Stage'), ('DEVELOPMENT', 'Development')], max_length=255, verbose_name='Mode')),
                ('container', models.CharField(max_length=255, null=True, verbose_name='Container ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.App', verbose_name='App')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
