# Generated by Django 2.2.7 on 2020-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='developmentSettings',
            field=models.TextField(blank=True, null=True, verbose_name='Development settings'),
        ),
        migrations.AlterField(
            model_name='app',
            name='productionSettings',
            field=models.TextField(blank=True, null=True, verbose_name='Production settings'),
        ),
        migrations.AlterField(
            model_name='app',
            name='stageSettings',
            field=models.TextField(blank=True, null=True, verbose_name='Stage settings'),
        ),
        migrations.AlterField(
            model_name='app',
            name='testScript',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/', verbose_name='Test script'),
        ),
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('REMOVED', 'Removed'), ('SUCCESSFULLY_DEPLOY', 'Success deploy'), ('ERROR_DEPLOY', 'Error deploy'), ('ERROR_REMOVE', 'Error remove'), ('TESTING', 'Testing')], max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('REMOVED', 'Removed'), ('SUCCESSFULLY_DEPLOY', 'Success deploy'), ('ERROR_DEPLOY', 'Error deploy'), ('ERROR_REMOVE', 'Error remove'), ('TESTING', 'Testing')], max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('REMOVED', 'Removed'), ('SUCCESSFULLY_DEPLOY', 'Success deploy'), ('ERROR_DEPLOY', 'Error deploy'), ('ERROR_REMOVE', 'Error remove'), ('TESTING', 'Testing')], max_length=255, verbose_name='Status'),
        ),
    ]
