# Generated by Django 2.2.7 on 2020-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200319_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='externalModification',
            field=models.BooleanField(default=False, verbose_name='External modification'),
        ),
    ]
