# Generated by Django 2.2.7 on 2020-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_app_externalmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='conflictMsg',
            field=models.TextField(blank=True, null=True, verbose_name='Conflict Message'),
        ),
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('REMOVED', 'Removed'), ('SUCCESSFULLY_DEPLOY', 'Successfully deploy'), ('ERROR_DEPLOY', 'Error deploy'), ('ERROR_REMOVE', 'Error remove'), ('TESTING', 'Testing'), ('SUCCESSFULLY_RELEASE', 'Successfully release')], max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('REMOVED', 'Removed'), ('SUCCESSFULLY_DEPLOY', 'Successfully deploy'), ('ERROR_DEPLOY', 'Error deploy'), ('ERROR_REMOVE', 'Error remove'), ('TESTING', 'Testing'), ('SUCCESSFULLY_RELEASE', 'Successfully release')], max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('REMOVED', 'Removed'), ('SUCCESSFULLY_DEPLOY', 'Successfully deploy'), ('ERROR_DEPLOY', 'Error deploy'), ('ERROR_REMOVE', 'Error remove'), ('TESTING', 'Testing'), ('SUCCESSFULLY_RELEASE', 'Successfully release')], max_length=255, verbose_name='Status'),
        ),
    ]
