# Generated by Django 2.2.7 on 2021-03-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_deploylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploylog',
            name='output',
            field=models.BinaryField(null=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='deploylog',
            name='stderr',
            field=models.BinaryField(null=True, verbose_name='Stderr'),
        ),
        migrations.AlterField(
            model_name='deploylog',
            name='stdout',
            field=models.BinaryField(null=True, verbose_name='Stdout'),
        ),
    ]
