# Generated by Django 2.2.7 on 2021-03-04 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210304_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylog',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time'),
            preserve_default=False,
        ),
    ]
