# Generated by Django 2.2.7 on 2021-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_deploylog_createdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylog',
            name='revision',
            field=models.CharField(max_length=255, null=True, verbose_name='server IP'),
        ),
        migrations.AddField(
            model_name='deploylog',
            name='serverIp',
            field=models.CharField(max_length=255, null=True, verbose_name='server IP'),
        ),
    ]
