# Generated by Django 2.2.7 on 2021-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210311_0150'),
    ]

    operations = [
        migrations.RenameModel('DeployLog', 'CommandLog'),
    ]
