# Generated by Django 2.2.7 on 2021-03-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210317_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='GUILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, null=True, verbose_name='IP')),
                ('platformSystem', models.CharField(max_length=255, null=True, verbose_name='Platform system')),
                ('platformVersion', models.CharField(max_length=255, null=True, verbose_name='Platform version')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Usernae')),
                ('server', models.CharField(db_index=True, max_length=255, null=True, verbose_name='server')),
                ('serverIp', models.CharField(max_length=255, null=True, verbose_name='server IP')),
                ('revision', models.CharField(max_length=255, null=True, verbose_name='Revision')),
                ('api', models.CharField(db_index=True, max_length=255, null=True, verbose_name='API')),
                ('data', models.CharField(max_length=255, null=True, verbose_name='Data')),
                ('output', models.BinaryField(null=True, verbose_name='Output')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
            ],
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='revision',
            field=models.CharField(max_length=255, null=True, verbose_name='Revision'),
        ),
    ]
