# Generated by Django 2.2.7 on 2021-03-31 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0022_auto_20210325_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guilog',
            name='api',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='createdTime',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='output',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='platformSystem',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='platformVersion',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='server',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='serverIp',
        ),
        migrations.RemoveField(
            model_name='guilog',
            name='username',
        ),
        migrations.AddField(
            model_name='guilog',
            name='logId',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guilog',
            name='logType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Remove',
        ),
    ]
