# Generated by Django 2.2.7 on 2021-03-31 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210331_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilog',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time'),
            preserve_default=False,
        ),
    ]
