# Generated by Django 2.2.7 on 2021-03-31 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_guilog_createdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilog',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='guilog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
