# Generated by Django 2.2.7 on 2021-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210331_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guilog',
            options={'verbose_name': 'GUI log', 'verbose_name_plural': 'GUI logs'},
        ),
        migrations.AddField(
            model_name='app',
            name='hchkProjectAPIKey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Healthchecks API key'),
        ),
        migrations.AddField(
            model_name='app',
            name='sentryDSN',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sentry DSN'),
        ),
    ]
