# Generated by Django 2.2.7 on 2021-04-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210331_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server which you want to deploy'),
        ),
        migrations.AddField(
            model_name='guilog',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.App', verbose_name='App'),
        ),
    ]
