# Generated by Django 2.2.7 on 2021-04-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210408_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Server which you want to deploy'),
        ),
    ]
