# Generated by Django 2.2.7 on 2021-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210408_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ifttt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project manager ifttt'),
        ),
    ]
