-- created using: ./enroll_db.sh -n CUSTOMERNAME -p 'p4ssw0rd123' -t
CREATE DATABASE CUSTOMERNAME_db;

CREATE USER 'CUSTOMERNAME_admin'@'localhost' IDENTIFIED BY 'p4ssw0rd123';
CREATE USER 'CUSTOMERNAME_admin'@'%' IDENTIFIED BY 'p4ssw0rd123';

GRANT ALL PRIVILEGES ON CUSTOMERNAME_db.* TO 'CUSTOMERNAME_admin'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON CUSTOMERNAME_db.* TO 'CUSTOMERNAME_admin'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test_CUSTOMERNAME_db.* TO 'CUSTOMERNAME_admin'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test_CUSTOMERNAME_db.* TO 'CUSTOMERNAME_admin'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
